package com.dulcehogar.ui;

import com.dulcehogar.business.Cuenta;
import com.dulcehogar.business.Socio;
import com.dulcehogar.business.GestorSocios;
import javax.swing.JOptionPane;

public class CancelarCuota extends javax.swing.JFrame implements VentanaMenu{
    GestorSocios gestor = new GestorSocios();

    public CancelarCuota() {
        initComponents();
    }
    @Override
    public void mostrarVentana() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroSocio = new javax.swing.JLabel();
        txtNumeroSocio = new javax.swing.JTextField();
        btnPagarCuota = new javax.swing.JButton();
        lblMontoCuota = new javax.swing.JLabel();
        txtCancelarCuota = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        lblPagarCuotaTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumeroSocio.setText("Ingrese N° de Socio");

        btnPagarCuota.setText("Pagar Cuota");
        btnPagarCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarCuotaActionPerformed(evt);
            }
        });

        lblMontoCuota.setText("Monto Cuota");

        btnVolver.setText("Volver al Menú");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblPagarCuotaTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPagarCuotaTitulo.setText("Pagar Cuota Mensual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(lblPagarCuotaTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMontoCuota)
                            .addComponent(txtCancelarCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnPagarCuota)))))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblPagarCuotaTitulo)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSocio)
                    .addComponent(lblMontoCuota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCancelarCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPagarCuota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarCuotaActionPerformed
        String numeroSocioStr = txtNumeroSocio.getText();
    if (numeroSocioStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar un número de socio.");
        return;
    }

    try {
        int numeroSocio = Integer.parseInt(numeroSocioStr);
        Socio socio = gestor.buscarSocioPorNumero(numeroSocio);

        if (socio != null) {
            String montoStr = txtCancelarCuota.getText();
            if (montoStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el monto de la cuota.");
                return;
            }

            int monto = Integer.parseInt(montoStr);

            boolean exito = gestor.actualizarCuotaSocio(numeroSocio, monto);

            if (exito) {
                JOptionPane.showMessageDialog(this, 
                    "El pago de la cuota por el monto de " + monto + " ha sido realizado correctamente para el socio N° " + numeroSocio + ".");
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar el pago.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un socio con el número " + numeroSocio + ".");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.");
    }
    }//GEN-LAST:event_btnPagarCuotaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_btnVolverActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagarCuota;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblMontoCuota;
    private javax.swing.JLabel lblNumeroSocio;
    private javax.swing.JLabel lblPagarCuotaTitulo;
    private javax.swing.JTextField txtCancelarCuota;
    private javax.swing.JTextField txtNumeroSocio;
    // End of variables declaration//GEN-END:variables
}
